spring:
  config:
    import: optional.:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}



  output:
    ansi:
      enabled: ALWAYS